# Travis-CI Build for libgit2
# see travis-ci.org for details

language: c

compiler:
  - gcc
#  - clang

# Settings to try
env:
 - PROJECT_NAME="aceofspades/libgit2"
 # COVERITY_SCAN_TOKEN
 - secure: "dp7Qh4jOVhBls5vswfoGK4oDVK3529YhR/hFSR/MpFI9mQhbfMaIDMOHfmscyfOkbBFDqDQ2k7TN9kgEjJZtcRKrQRVKgPKU6CyU11Ff1uQt/pYsiVwL17SXuIucZqSSSzBH9gHxkU6Qzef4gu9lJDmUrwbXi4RI78a6WrQusEo="
# global:
# matrix:
#  - OPTIONS="-DTHREADSAFE=ON -DCMAKE_BUILD_TYPE=Release"
#  - OPTIONS="-DBUILD_CLAR=ON -DBUILD_EXAMPLES=ON"

addons:
  coverity_scan:
    project:
      name: aceofspades/libgit2
      slug: aceofspades/libgit2
      version: 0.0
      description: The Git linkable library
    email: nobody@nowhere.com
    build_command: cmake --build .
    branch_pattern: coverity_scan
    build_script_url: https://gist.github.com/aceofspades/4bd0dd25f2cbfde5093c/raw

#matrix:
# fast_finish: true
# include:
#   - compiler: i586-mingw32msvc-gcc
#     env: OPTIONS="-DBUILD_CLAR=OFF -DWIN32=ON -DMINGW=ON"
#   - compiler: gcc
# allow_failures:

install:
 - sudo apt-get -qq update
 - sudo apt-get -qq install cmake libssh2-1-dev openssh-client openssh-server

# Run the Build script and tests
script:
# - script/cibuild.sh
  - uname -a
  - echo "shell: $0"
  - ls -la /bin/sh
  - env

# Run Tests
#after_success:
# - sudo apt-get -qq install valgrind
# - valgrind --leak-check=full --show-reachable=yes --suppressions=./libgit2_clar.supp _build/libgit2_clar -ionline

# Only watch the development and coverity_scan branches
branches:
 only:
   #- development
   - coverity_scan
   - test

# Notify development list when needed
notifications:
 irc:
  channels:
    - irc.freenode.net#libgit2
  on_success: change
  on_failure: always
  use_notice: true
  skip_join: true
 campfire:
  on_success: always
  on_failure: always
  rooms:
   - secure: "sH0dpPWMirbEe7AvLddZ2yOp8rzHalGmv0bYL/LIhVw3JDI589HCYckeLMSB\n3e/FeXw4bn0EqXWEXijVa4ijbilVY6d8oprdqMdWHEodng4KvY5vID3iZSGT\nxylhahO1XHmRynKQLOAvxlc93IlpVW38vQfby8giIY1nkpspb2w="
