# Travis-CI Build for libgit2
# see travis-ci.org for details

language: c

compiler:
  - gcc
#  - clang

env:
  global:
  - PROJECT_NAME="aceofspades/libgit2"
  - TRAVIS_TEST_RESULT=0
  - OWNER_EMAIL=nobody@nowhere.com
  # COVERITY_SCAN_TOKEN via "travis encrypt" using the repo's public key
  - secure: "MixjiXqN5ckgTDGydYC3a0xLFOTcJOrfQiU4x47HF87WzdcnTQgPGP51r4wVL13JWKSbzrE+bmHJ3gItewhnvkaSu3SGHZGZZX+Pma5sgJtqv6cLkjwC9ceMhjJVANWoFoblbyI9tMUoBcABqxE1mBts6rtJnLyC6aqFDvSHqMY="

addons:
  coverity_scan:
    project:
      name: "aceofspades/libgit2"
      description: "Your project description here 4"
    #notification_email: "scan-admin@coverity.com"
    build_command_prepend: "mkdir -p _build && cd _build && cmake .. -DTHREADSAFE=ON"
    build_command: "cmake --build ."
    branch_pattern: coverity_scan

#  matrix:
#    - COVERITY_SCAN=1
#   - OPTIONS="-DTHREADSAFE=ON -DCMAKE_BUILD_TYPE=Release"
#   - OPTIONS="-DBUILD_CLAR=ON -DBUILD_EXAMPLES=ON"

matrix:
#  fast_finish: true
#  include:
#    - compiler: i586-mingw32msvc-gcc
#      env: OPTIONS="-DBUILD_CLAR=OFF -DWIN32=ON -DMINGW=ON"
#    - compiler: gcc
#      env: COVERITY_SCAN=1
#  allow_failures:
#    - env: COVERITY_SCAN=1
#  - env: COVERITY_SCAN=1

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install cmake libssh2-1-dev openssh-client openssh-server

# Run the Build script and tests
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then script/cibuild.sh ; fi

# Run Tests
after_success:
  - sudo apt-get -qq install valgrind
  - valgrind --leak-check=full --show-reachable=yes --suppressions=./libgit2_clar.supp _build/libgit2_clar -ionline

# Only watch the development and coverity_scan branches
branches:
  only:
    - development
    - coverity_scan

# Notify development list when needed
#notifications:
# irc:
#  channels:
#    - irc.freenode.net#libgit2
#  on_success: change
#  on_failure: always
#  use_notice: true
#  skip_join: true
# campfire:
#  on_success: always
#  on_failure: always
#  rooms:
#   - secure: "sH0dpPWMirbEe7AvLddZ2yOp8rzHalGmv0bYL/LIhVw3JDI589HCYckeLMSB\n3e/FeXw4bn0EqXWEXijVa4ijbilVY6d8oprdqMdWHEodng4KvY5vID3iZSGT\nxylhahO1XHmRynKQLOAvxlc93IlpVW38vQfby8giIY1nkpspb2w="
